export const EDGE_FAMILIES = [
  {
    family: 'Judicial Treatment',
    color: '#f59e0b',
    narrative: 'How courts have adopted, distinguished, or departed from this authority.',
    types: [
      {
        value: 'followed', label: 'Followed', signal: 'positive', class: 'chip-positive',
        hint: 'Ratio applied as binding precedent',
        description: 'The court expressly adopted the ratio decidendi of the cited authority as binding precedent.',
        guidance: 'Use when the judgment directly follows and applies the legal principle established in the target authority.',
        example: 'Maneka Gandhi v. Union of India followed Rustom Cavasjee Cooper v. Union of India',
      },
      {
        value: 'applied', label: 'Applied', signal: 'positive', class: 'chip-positive',
        hint: 'Principle used in new context',
        description: 'The court applied the legal principle from the cited authority to the facts of the present case.',
        guidance: 'Use when the principle is applied but not necessarily as binding — may be persuasive application.',
        example: 'Vishaka v. State of Rajasthan applied CEDAW principles to workplace harassment',
      },
      {
        value: 'approved', label: 'Approved', signal: 'positive', class: 'chip-positive',
        hint: 'Endorsed by higher authority',
        description: 'A higher court endorsed or affirmed the reasoning of the cited authority.',
        guidance: 'Use when an appellate or constitutional court approves a lower court decision.',
        example: 'Supreme Court approved the reasoning in Delhi High Court\'s Naz Foundation judgment',
      },
      {
        value: 'explained', label: 'Explained', signal: 'neutral', class: 'chip-neutral',
        hint: 'Clarified scope or meaning',
        description: 'The court clarified or elaborated the scope and meaning of the cited authority without altering its application.',
        guidance: 'Use when a judgment explains what an earlier decision actually held — resolving ambiguity.',
        example: 'A.K. Gopalan explained the scope of Article 21 before Maneka Gandhi expanded it',
      },
      {
        value: 'referred_to', label: 'Referred To', signal: 'neutral', class: 'chip-neutral',
        hint: 'Mentioned without full adoption',
        description: 'The court mentioned the cited authority in passing — not as a basis for the decision.',
        guidance: 'Use for citations that appear in the judgment but do not drive the ratio.',
        example: 'The court referred to various Law Commission reports in its obiter',
      },
      {
        value: 'distinguished', label: 'Distinguished', signal: 'neutral', class: 'chip-neutral',
        hint: 'Facts or context differ materially',
        description: 'The court held that the cited authority was decided on materially different facts and therefore does not apply.',
        guidance: 'Use when a court acknowledges a precedent but finds it inapplicable due to factual differences.',
        example: 'ADM Jabalpur distinguished from Habeas Corpus cases involving non-emergency contexts',
      },
      {
        value: 'doubted', label: 'Doubted', signal: 'negative', class: 'chip-negative',
        hint: 'Correctness questioned',
        description: 'The court expressed doubt about the correctness of the cited authority without formally overruling it.',
        guidance: 'Use when judicial skepticism is expressed — the authority remains technically valid but weakened.',
        example: 'Several benches doubted the continued applicability of ADM Jabalpur before formal overruling',
      },
      {
        value: 'not_followed', label: 'Not Followed', signal: 'negative', class: 'chip-negative',
        hint: 'Declined to apply',
        description: 'The court declined to follow the cited authority, typically by a court not bound by it.',
        guidance: 'Use when a coordinate or lower court departs from a precedent — distinct from overruling.',
        example: 'A High Court declined to follow another High Court\'s interpretation of Section 498A',
      },
      {
        value: 'overruled', label: 'Overruled', signal: 'negative', class: 'chip-negative',
        hint: 'No longer good law',
        description: 'A higher court has expressly overruled the cited authority — it is no longer good law.',
        guidance: 'Use only for formal overruling by a competent court. The most significant negative treatment.',
        example: 'Puttaswamy overruled the surveillance-permissive aspects of M.P. Sharma and Kharak Singh',
      },
    ],
  },
  {
    family: 'Legislative Lineage',
    color: '#8b5cf6',
    narrative: 'How statutes succeed, modify, or supersede one another through legislative action.',
    types: [
      {
        value: 'replaces', label: 'Replaces', signal: 'neutral', class: 'chip-legislative',
        hint: 'Successor legislation',
        description: 'The source statute entirely replaces the target statute as its successor.',
        guidance: 'Use when a new Act replaces an older one in its entirety (e.g., BNS replacing IPC).',
        example: 'Bharatiya Nyaya Sanhita (BNS) replaces Indian Penal Code (IPC)',
      },
      {
        value: 'amends', label: 'Amends', signal: 'neutral', class: 'chip-legislative',
        hint: 'Modifies specific provisions',
        description: 'The source legislation amends or modifies specific provisions of the target statute.',
        guidance: 'Use for amendment acts that alter portions of an existing statute.',
        example: 'Criminal Law (Amendment) Act 2013 amends Indian Penal Code',
      },
      {
        value: 'repeals', label: 'Repeals', signal: 'negative', class: 'chip-negative',
        hint: 'Formally abolished',
        description: 'The source legislation formally repeals the target statute — it ceases to have legal force.',
        guidance: 'Use when a statute is explicitly repealed by legislative action.',
        example: 'The Repealing and Amending Act 2016 repealed several obsolete statutes',
      },
      {
        value: 'subordinate_to', label: 'Subordinate To', signal: 'neutral', class: 'chip-legislative',
        hint: 'Delegated legislation under parent Act',
        description: 'The source is subordinate/delegated legislation made under the authority of the target parent Act.',
        guidance: 'Use for rules, regulations, and notifications issued under a parent statute.',
        example: 'Companies (Share Capital) Rules are subordinate to the Companies Act 2013',
      },
      {
        value: 'overrides', label: 'Overrides', signal: 'negative', class: 'chip-negative',
        hint: 'Takes precedence over conflicting provisions',
        description: 'The source legislation overrides conflicting provisions in the target through a non-obstante clause.',
        guidance: 'Use when a statute contains "notwithstanding anything contained in" language overriding another.',
        example: 'SARFAESI Act overrides conflicting provisions of the Limitation Act',
      },
    ],
  },
  {
    family: 'Conceptual',
    color: '#3b82f6',
    narrative: 'How legal ideas, doctrines, and principles relate to and build upon each other.',
    types: [
      {
        value: 'interprets', label: 'Interprets', signal: 'positive', class: 'chip-conceptual',
        hint: 'Provides authoritative meaning',
        description: 'The source provides authoritative judicial interpretation of the target provision or concept.',
        guidance: 'Use when a judgment gives definitive meaning to a statutory provision or constitutional article.',
        example: 'Maneka Gandhi interprets Article 21 to include procedural fairness',
      },
      {
        value: 'establishes', label: 'Establishes', signal: 'positive', class: 'chip-conceptual',
        hint: 'Creates new legal doctrine',
        description: 'The source establishes a new legal doctrine, test, or principle derived from the target.',
        guidance: 'Use when a judgment creates a new legal standard or doctrinal framework.',
        example: 'Kesavananda Bharati establishes the Basic Structure Doctrine from constitutional interpretation',
      },
      {
        value: 'codifies', label: 'Codifies', signal: 'positive', class: 'chip-conceptual',
        hint: 'Judge-made law enacted as statute',
        description: 'The source statute codifies a principle previously established through judicial precedent.',
        guidance: 'Use when legislation formally enacts what was previously judge-made law.',
        example: 'Consumer Protection Act 2019 codifies various consumer rights established through case law',
      },
      {
        value: 'exception_to', label: 'Exception To', signal: 'cautionary', class: 'chip-neutral',
        hint: 'Carve-out from general rule',
        description: 'The source represents an exception or carve-out from the general rule established by the target.',
        guidance: 'Use when a provision creates an exception to a broader legal principle.',
        example: 'Section 80 CPC (notice requirement) is exception to general right to sue the government',
      },
      {
        value: 'governed_by', label: 'Governed By', signal: 'neutral', class: 'chip-conceptual',
        hint: 'Primary governing legislation',
        description: 'The source concept or subject area is primarily governed by the target statute.',
        guidance: 'Use to link a legal topic to its primary governing legislation.',
        example: 'Contract formation in India is governed by the Indian Contract Act 1872',
      },
    ],
  },
  {
    family: 'Structural',
    color: '#64748b',
    narrative: 'Hierarchical and organizational relationships within the knowledge structure.',
    types: [
      {
        value: 'part_of', label: 'Part Of', signal: 'neutral', class: 'chip-structural',
        hint: 'Component of larger structure',
        description: 'The source is a constituent part of the target within a hierarchical structure.',
        guidance: 'Use for chapters within statutes, sections within chapters, etc.',
        example: 'Section 302 IPC is part of Chapter XVI (Offences Affecting the Human Body)',
      },
    ],
  },
];
